#!/usr/bin/env bash

echo "Starting InsightLake ..."

export JAVA_HOME=/usr/java/default

if [ "$JAVA_HOME" != "" ]; then
    #echo "run java in $JAVA_HOME"
    JAVA_HOME=$JAVA_HOME
fi

if [ "$JAVA_HOME" = "" ]; then
    echo "Error: JAVA_HOME is not set."
    exit 1
fi

JAVA=$JAVA_HOME/bin/java
JAVA_HEAP_MAX=-Xmx1000m

PRG="${0}"

while [ -h "${PRG}" ]; do
  ls=`ls -ld "${PRG}"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "${PRG}"`/"$link"
  fi
done

EDP_HOME=`dirname ${PRG}`
EDP_HOME=`cd ${EDP_HOME}/..;pwd`

mkdir -p $EDP_HOME/logs
cd $EDP_HOME/logs


echo "$EDP_HOME"

CLASSPATH="$EDP_HOME/conf:$EDP_HOME/libs:$EDP_HOME/bin"

for f in $EDP_HOME/libs/*.jar; do
    CLASSPATH=${CLASSPATH}:$f;
done


for ARGUMENT in "$@"
do

    KEY=$(echo $ARGUMENT | cut -f1 -d=)
    VALUE=$(echo $ARGUMENT | cut -f2 -d=)   

    case "$KEY" in
            --localPath)              localPath=${VALUE} ;;
            --file)    file=${VALUE} ;; 
            --type)        type=${VALUE};;  
            *)   
    esac    


done

echo "localPath = $localPath"
echo "file = $file"
echo "type = $type"

echo "Starting App ..."
java -jar $EDP_HOME/libs/edp-kafka-cli-0.0.1-SNAPSHOT-jar-with-dependencies.jar --localPath=$localPath --file=$file --type=$type&





